name: CI

on:
  pull_request:
    branches: [ main ]

jobs:

  test:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        pip install pandas psycopg2-binary
        pip install flake8 black pytest

    - name: Lint
      run: |
        flake8 .

    - name: Format check
      run: |
        black --check .

    - name: Run tests
      run: |
        pytest